const ARTWORKS = [
  {"id":"work-12","title":"I Like to Make Men Cry","year":2026,"price":960,"status":"available","collection":"Studio Series","size":"— × — cm","image":"images/work-12.JPG","thumbnail":"images/thumbs/work-12.webp","text":"","ar":{"enabled":false,"file":"ar/work-12.usdz","width":0,"height":0}},
  {"id":"work-13","title":"A Night at the Espy","year":2026,"price":0,"status":"na","collection":"Studio Series","size":"— × — cm","image":"images/work-13.png","thumbnail":"images/thumbs/work-13.webp","text":"","ar":{"enabled":false,"file":"ar/work-13.usdz","width":0,"height":0}},
  {"id":"work-14","title":"","year":2026,"price":1240,"status":"available","collection":"Studio Series","size":"120 × 90 cm","image":"images/work-14.png","thumbnail":"images/thumbs/work-14.webp","text":"","ar":{"enabled":true,"file":"ar/work-14.usdz","width":120,"height":90}},
  {"id":"work-20","title":"Untitled","year":2026,"price":0,"status":"available","collection":"","size":"— × — cm","image":"images/work 20.png","thumbnail":"images/work 20.png","text":"","ar":{"enabled":false,"file":"ar/work-20.usdz","width":0,"height":0}},
  {"id":"work-21","title":"Untitled","year":2026,"price":0,"status":"available","collection":"","size":"— × — cm","image":"images/work 21.png","thumbnail":"images/work 21.png","text":"","ar":{"enabled":false,"file":"ar/work-21.usdz","width":0,"height":0}},
  {"id":"work-22","title":"Untitled","year":2026,"price":0,"status":"available","collection":"","size":"— × — cm","image":"images/work 22.png","thumbnail":"images/work 22.png","text":"","ar":{"enabled":false,"file":"ar/work-22.usdz","width":0,"height":0}},
  {"id":"work-08","title":"Yung Brother","year":2026,"price":175,"status":"available","collection":"BS","size":"30 × 40 cm","image":"images/work-08.png","thumbnail":"images/thumbs/work-08.webp","text":"","ar":{"enabled":true,"file":"ar/work-08.usdz","width":30,"height":40}},
  {"id":"work-09","title":"Untitled","year":2026,"price":0,"status":"available","collection":"","size":"— × — cm","image":"images/work-09.png","thumbnail":"images/thumbs/work-09.webp","text":"","ar":{"enabled":false,"file":"ar/work-09.usdz","width":0,"height":0}},
  {"id":"work-10","title":"Untitled","year":2026,"price":0,"status":"available","collection":"","size":"— × — cm","image":"images/work-10.png","thumbnail":"images/thumbs/work-10.webp","text":"","ar":{"enabled":false,"file":"ar/work-10.usdz","width":0,"height":0}},
  {"id":"work-11","title":"Untitled","year":2026,"price":0,"status":"available","collection":"","size":"— × — cm","image":"images/work-11.png","thumbnail":"images/thumbs/work-11.webp","text":"","ar":{"enabled":false,"file":"ar/work-11.usdz","width":0,"height":0}},
  {"id":"work-01","title":"Untitled","year":2024,"price":660,"status":"available","collection":"Studio Series","size":"60 × 90 cm","image":"images/work-01.png","thumbnail":"images/thumbs/work-01.webp","text":"","ar":{"enabled":true,"file":"ar/work-01.usdz","width":60,"height":90}},
  {"id":"work-02","title":"People","year":2024,"price":850,"status":"sold","collection":"Studio Series","size":"40 × 50 cm","image":"images/work-02.png","thumbnail":"images/thumbs/work-02.webp","text":"","ar":{"enabled":true,"file":"ar/work-02.usdz","width":40,"height":50}},
  {"id":"work-03","title":"Untitled","year":2023,"price":0,"status":"na","collection":"Field Studies","size":"— × — cm","image":"images/work-03.png","thumbnail":"images/thumbs/work-03.webp","text":"","ar":{"enabled":false,"file":"ar/work-03.usdz","width":0,"height":0}},
  {"id":"work-04","title":"Her Face","year":2023,"price":470,"status":"available","collection":"","size":"30 × 40 cm","image":"images/work-04.png","thumbnail":"images/thumbs/work-04.webp","text":"","ar":{"enabled":true,"file":"ar/work-04.usdz","width":30,"height":40}},
  {"id":"work-05","title":"ArtShed","year":2025,"price":2400,"status":"available","collection":"Studio Series","size":"70 × 90cm","image":"images/work-05.png","thumbnail":"images/thumbs/work-05.webp","text":"","ar":{"enabled":true,"file":"ar/work-05.usdz","width":70,"height":90}},
  {"id":"work-06","title":"Older Sister","year":2022,"price":225,"status":"sold","collection":"BS","size":"60 × 60 cm","image":"images/work-06.png","thumbnail":"images/thumbs/work-06.webp","text":"","ar":{"enabled":true,"file":"ar/work-06.usdz","width":60,"height":60}},
  {"id":"work-07","title":"Untitled","year":2025,"price":125,"status":"available","collection":"Painters Retreat","size":"15 × 10 cm","image":"images/work-07.png","thumbnail":"images/thumbs/work-07.webp","text":"","ar":{"enabled":true,"file":"ar/work-07.usdz","width":15,"height":10}}
];