(function(){
  const grid=document.getElementById("grid");
  if(!grid)return;
  const zoomControl=document.getElementById("zoom-control");
  const levels=["zoom","normal","overview"];
  const isTouchDevice=window.matchMedia("(hover:none) and (pointer:coarse)").matches;
  const STATE_KEY="kritor-store-state";

  const savedState=(()=>{try{return JSON.parse(sessionStorage.getItem(STATE_KEY)||"null")}catch(e){return null}})();
  let level=savedState&&Number.isInteger(savedState.level)?Math.max(0,Math.min(levels.length-1,savedState.level)):(isTouchDevice?0:2);
  let pinchStart=null,gestureStartScale=null,gestureHandled=false;

  function saveState(){
    try{sessionStorage.setItem(STATE_KEY,JSON.stringify({level,scrollY:window.scrollY}))}catch(e){}
  }

  function applyLevel(n){
    level=(n+levels.length)%levels.length;
    grid.classList.remove("view-normal","view-zoom","view-overview");
    grid.classList.add(`view-${levels[level]}`);
    if(zoomControl){
      zoomControl.textContent=level===2?"−":"+";
      zoomControl.setAttribute("aria-label",level===2?"Return to larger store view":"Reduce artwork size");
    }
    saveState();
  }

  /* The store lives at /store/, so item-relative asset paths need rooting. */
  function assetPath(path){return path?(path.startsWith("/")||/^https?:/.test(path)?path:"/"+path):""}

  /* shop/<id>/01.png -> /shop/<id>/thumbs/01.webp */
  function thumbPath(first){
    if(!first)return"";
    const slash=first.lastIndexOf("/"),dot=first.lastIndexOf(".");
    if(slash===-1||dot<=slash)return assetPath(first);
    return assetPath(`${first.slice(0,slash)}/thumbs/${first.slice(slash+1,dot)}.webp`);
  }

  function makeTile(item){
    const a=document.createElement("a"),i=document.createElement("img");
    const first=(item.images||[])[0]||"";
    const full=assetPath(first),thumb=thumbPath(first);
    a.className="tile";
    a.dataset.workId=item.id;
    a.href=`/shop/${encodeURIComponent(item.id)}/`;
    a.setAttribute("aria-label",`${item.title||item.id}${item.year?", "+item.year:""}`);
    if(soldOut(item))a.classList.add("is-sold-out");
    i.src=thumb||full;
    i.alt=item.title||"";
    i.loading="lazy";
    i.decoding="async";
    /* Thumbnails are generated by CI after the push, so fall back to the
       full image until the workflow has caught up. */
    i.onerror=function(){if(full&&i.src.indexOf(full)===-1)i.src=full};
    a.appendChild(i);
    return a;
  }

  function soldOut(item){return !(Number.isFinite(item.stock)?item.stock:1)}

  function storeItems(){
    if(typeof SHOP_ITEMS==="undefined"||!Array.isArray(SHOP_ITEMS))return[];
    return SHOP_ITEMS.slice();
  }

  function render(){
    grid.innerHTML="";
    const items=storeItems();
    if(!items.length){
      grid.innerHTML='<p class="store-empty">Nothing for sale right now.</p>';
      applyLevel(level);
      return;
    }
    items.forEach(item=>grid.appendChild(makeTile(item)));
    applyLevel(level);
    if(savedState&&Number.isFinite(savedState.scrollY))requestAnimationFrame(()=>window.scrollTo(0,savedState.scrollY));
  }

  render();

  grid.addEventListener("click",e=>{if(e.target.closest("a.tile"))saveState()});
  if(zoomControl)zoomControl.addEventListener("click",()=>applyLevel(level+1));

  function pd(t){const a=t[0],b=t[1];return Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY)}
  grid.addEventListener("gesturestart",e=>{gestureStartScale=e.scale||1;gestureHandled=false;e.preventDefault()},{passive:false});
  grid.addEventListener("gesturechange",e=>{
    e.preventDefault();
    if(gestureHandled||gestureStartScale===null)return;
    const s=e.scale||1;
    if(Math.abs(s-gestureStartScale)>.12){applyLevel(level+(s>gestureStartScale?-1:1));gestureHandled=true}
  },{passive:false});
  grid.addEventListener("gestureend",e=>{e.preventDefault();gestureStartScale=null;gestureHandled=false},{passive:false});
  grid.addEventListener("touchstart",e=>{if(e.touches.length===2)pinchStart=pd(e.touches)},{passive:true});
  grid.addEventListener("touchmove",e=>{
    if(e.touches.length!==2||pinchStart===null)return;
    const d=pd(e.touches)-pinchStart;
    if(Math.abs(d)>80){applyLevel(level+(d>0?-1:1));pinchStart=pd(e.touches)}
  },{passive:true});
  grid.addEventListener("touchend",()=>pinchStart=null,{passive:true});
})();
