/* KRITOR — responsive tile images.

   Builds the <picture> for a grid tile from IMAGE_MANIFEST (generated by
   tools/build-images.py at deploy time).

   Three things make the landing screen feel instant rather than blank:

   1. The LQIP is a ~200 byte data URI baked into the manifest, so a tile paints
      the work's colours on the first frame with no network request at all.
   2. srcset lets a phone fetch a phone-sized rendition instead of the print
      original — around 6-30 KB rather than 1-2 MB.
   3. The first screenful is eager and high priority; everything below is lazy,
      so the visible rows are not queued behind the ones nobody has scrolled to.

   If the manifest is missing — someone opened the repo without running the
   build — this degrades to a plain <img> of the original, so the page is never
   broken by a missing build step. */
(function () {
  "use strict";

  /* A starting guess only. The zoom control changes the column count at
     runtime, so a fixed sizes attribute is wrong at two of the three levels —
     applySizes() below replaces it with the real figure. */
  const SIZES = "(max-width: 699px) 50vw, (max-width: 1199px) 34vw, 25vw";

  function columnsOf(grid) {
    return getComputedStyle(grid).gridTemplateColumns.split(" ").filter(Boolean).length || 1;
  }

  /* Tell the browser how wide a tile actually is now, so srcset picks the right
     rendition instead of one chosen for a different zoom level. Call whenever
     the column count changes. */
  function applySizes(grid) {
    if (!grid) return;
    const sizes = `${Math.round(100 / columnsOf(grid))}vw`;
    grid.querySelectorAll("picture source, picture img").forEach(el => { el.sizes = sizes; });
  }

  /* How many tiles to load eagerly: roughly the first two rows. At one column
     on a phone that is 2 full-width images, not 8 — the difference between a
     fast first screen and eagerly fetching most of the catalogue. */
  function eagerCount(grid) {
    if (!grid) return 4;
    return Math.max(2, Math.min(24, columnsOf(grid) * 2));
  }

  function manifest() {
    return typeof IMAGE_MANIFEST !== "undefined" ? IMAGE_MANIFEST : null;
  }

  function lookup(path) {
    const all = manifest();
    if (!all || !path) return null;
    return all[path] || all[path.replace(/^\//, "")] || null;
  }

  function rooted(url) {
    return url.startsWith("/") || /^https?:/.test(url) ? url : "/" + url;
  }

  function srcsetFor(variants) {
    return variants.map(v => `${encodeURI(rooted(v.url))} ${v.w}w`).join(", ");
  }

  /* Builds the element to put inside a tile. Returns a <picture> when the
     manifest has the image, and a bare <img> when it does not. */
  function build(path, options) {
    const opts = options || {};
    const entry = lookup(path);
    const img = document.createElement("img");

    img.alt = opts.alt || "";
    img.decoding = "async";

    if (opts.eager) {
      img.loading = "eager";
      img.setAttribute("fetchpriority", "high");
    } else {
      img.loading = "lazy";
    }

    if (!entry || !entry.webp || !entry.webp.length) {
      img.src = encodeURI(rooted(path));
      return img;
    }

    /* Smallest rendition as src: it is what a browser ignoring srcset gets,
       and it is the cheapest thing that is still a real image. */
    const widest = entry.webp[entry.webp.length - 1];
    img.src = encodeURI(rooted(entry.webp[0].url));
    img.srcset = srcsetFor(entry.webp);
    img.sizes = SIZES;
    img.width = widest.w;
    img.height = Math.round(widest.w / (entry.ratio || 1));

    const picture = document.createElement("picture");

    if (entry.avif && entry.avif.length) {
      const avif = document.createElement("source");
      avif.type = "image/avif";
      avif.srcset = srcsetFor(entry.avif);
      avif.sizes = SIZES;
      picture.appendChild(avif);
    }

    const webp = document.createElement("source");
    webp.type = "image/webp";
    webp.srcset = srcsetFor(entry.webp);
    webp.sizes = SIZES;
    picture.appendChild(webp);

    picture.appendChild(img);

    /* The blur sits on the picture, behind the image, and is dropped once the
       real pixels are painted. */
    if (entry.lqip) {
      picture.classList.add("is-loading");
      picture.style.backgroundImage = `url("${entry.lqip}")`;
      const done = () => picture.classList.remove("is-loading");
      if (img.complete && img.naturalWidth) done();
      else {
        img.addEventListener("load", done, {once: true});
        img.addEventListener("error", done, {once: true});
      }
    }

    return picture;
  }

  /* The smallest rendition at least `targetWidth` wide, for the places that
     need one URL rather than a whole <picture> — the series carousel, the bag
     line thumbnails, the work page's main image. Falls back to the original. */
  function pick(path, targetWidth) {
    const entry = lookup(path);
    if (!entry || !entry.webp || !entry.webp.length) return encodeURI(rooted(path || ""));
    const wanted = targetWidth || 480;
    const match = entry.webp.find(v => v.w >= wanted) || entry.webp[entry.webp.length - 1];
    return encodeURI(rooted(match.url));
  }

  /* The inline blur for a path, or "" when the manifest has no entry. */
  function placeholder(path) {
    const entry = lookup(path);
    return entry && entry.lqip ? entry.lqip : "";
  }

  window.KritorTileImage = {build, pick, placeholder, lookup, eagerCount, applySizes, SIZES};
})();
